ДЗ по второму воркшопу
semiletkin/rtg-items-api pull request #1
Opened 2021-10-26 16:27 UTC by semiletkin

2021-10-30 21:04 UTC, Maklayna requested changes

2021-10-31 19:23 UTC, semiletkin commented on internal/app/consumer/dbase.go
> +					c.repoLocker.Lock()
ну так то репозиторий и в консьюмере, и в продьюсере, кто ж знает как он реализован, разные горутины, поэтому лок. А обычный мьютекс - на воркшопе обсуждали, и, насколько я понял, пока не известно распределение между записью/чтением лучше не использовать rwmutex.

2021-10-31 19:31 UTC, semiletkin commented on internal/app/producer/kafka.go
> +func (p *producer) updater(batch []uint64) error {
В домашке на схеме были updaters и cleaners - ноги оттуда.

2021-11-01 07:05 UTC, Maklayna commented on internal/app/consumer/dbase.go
> +					c.repoLocker.Lock()
ну так конкурентное чтение не вызывает проблем, а записи нового репозитариия нигде нет.  rwmutex в подавляющем большинстве подобных случаев будет лучше, так как дает неограниченное число рид локов.

2021-11-01 07:12 UTC, Maklayna approved these changes

2021-11-03 18:25 UTC, merged